### ISSUE TITLE
Should Queue.clear() delete the Objects, not just remove them from the Queue?

### ISSUE THREAD

**Issue by drakstik** [hakjoonlee/CS4500-A1P2#11]
In your test_queue_clear() the objects are being deleted after they've been cleared from the Queue. I'm assuming you want us to not delete these objects in the clear() function, but I think that if a user is clearing their queue, it is because they don't need those objects anymore or have already copied those objects elsewhere. 

Another argument is that if we do not instantiate an object and pass it to be enqueued like so:

Queue.enqueue(new Object());

Then that object has no way of being referenced to when trying to manually delete it from memory later.

**Comment by andrewstam** [comment]
Thanks for raising this concern. My partner and I discussed this and feel that a clearing a Queue should not delete its elements. We shouldn't assume that clearing a Queue indicates that a user doesn't need those Objects anymore. Users might have one Object as a part of two Queues, or could want to use the Object even after clearing the Queue. We would still want to be able to reference that Object after the Queue is cleared. The responsibility of deleting an Object should be for the user that instantiates it rather than relying on the Queue to do it for them.

We can keep this issue open in case others have more thoughts on this, but for now we plan to stay with the current design.

**Comment by kaylindevchand** [comment]
I agree with @andrewstam

**Comment by drakstik** [comment]
OK cool, thanks for the explanation. Makes sense to go in that direction. 

But for your own notes, this implementation retains that issue of uninstantiated floating memory that I mentioned above (no implementation is perfect).
