### ISSUE TITLE
Need Strict String Queues

### ISSUE THREAD

**Issue by csstransky** [hakjoonlee/CS4500-A1P2#4]
After looking at the spec for assignment 2, we need to have a queue that strictly deals with strings. 
From the spec:

> The Queue class should support normal push and pop operations, the values that need to be supported are Strings and Objects.

We've actually added a pull request that does just that here: #3

**Comment by csstransky** [comment]
Just to add a little more here, your implementation of only using Objects absolutely makes sense (since a String is an Object), but we just want to make sure we don't lose any points from TAs by being extra explicit with what's happening in the spec.

**Comment by hakjoonlee** [comment]
We definitely understand your concern about having a separate StrQueue class that deals with strings, as this was an issue we faced when creating the API. We're still not convinced that we need a separate Queue interface for Strings, since the only functionality that a new class would provide is type-checking to make sure all elements are Strings. When adding new types, this would mean we would continue to add new interfaces. We felt that it should be the implementation's job to perform type-checking as elements are added to the Queue, so we believe a separate class that deals strictly with Strings should be part of the implementation and not the interface.

**Comment by csstransky** [comment]
So if I'm understanding correctly, the user needs to make their own StrQueue, IntQueue, etc. that enforces the type of the queue OUTSIDE the queue.h? 

Eventually we want to add tests strictly for string queues, should we create a StrQueue class inside of test-queue.cpp, or create a "StrQueue" variable of type Queue that checks that every Object being passed into the Queue is a String?

Looking at Jan's Object class ([https://piazza.com/class/k51bluky59n2jr?cid=166](https://piazza.com/class/k51bluky59n2jr?cid=166)), there really isn't much to tell what type an Object is, unless we use something dirty like dynamically casting a type and seeing if it was correctly cast to a String, example here: [https://stackoverflow.com/questions/500493/c-equivalent-of-instanceof](https://stackoverflow.com/questions/500493/c-equivalent-of-instanceof)

How would you implement a string queue?
Will scope creep occur if we decide to add StrQueue to Queue now?

**Comment by csstransky** [comment]
Here are some Piazza questions that might help:
[https://piazza.com/class/k51bluky59n2jr?cid=331](https://piazza.com/class/k51bluky59n2jr?cid=331)
[https://piazza.com/class/k51bluky59n2jr?cid=341](https://piazza.com/class/k51bluky59n2jr?cid=341)

Jan decided to be more direct with answering questions directly and said this:
> This boils down to the question whether I am allowed to write this:
> 
> `String  result  =  my_string_queue.pop();`
> 
> If you want to support this you will be pushed in one direction, if you don't you may have other choices.

I would argue that it's much nicer _to have the option_ to grab strings from a Queue if we desire, instead of having to cast Objects, though you can argue the problem of scope creep. For our purposes, we'll have to have some way of testing Strings, and I would prefer to avoid having to cast things, _in my opinion_.

Jan gives this response on dealing with CwC and its absence of generics:
> Again play this out. You seem stuck on partial designs. 
> 
>  
> 
> Imagine an array of int and that we want to read and write to it.  What is the better design?
> 
>  
> 
> ```
> ia.push_back( 42 );
> int r = ia.get( 0 );
> ```
> 
>  
> 
> or 
> 
>  
> 
> ```
> ia.push_back( (void*) 42 );
> int r = (int) ia.get( 0 );
> ```
> 
>  
> 
> Functionally they are the same but in terms of correctness and ease of use they are miles apart.
> 
>  
> 
> As a side note: the idea of using void* to store any value is not portable.  The size of a void* is architecture dependent. There are still embedded boards where a void* is 16 bits. Not enough to store an int.

...

> Both of these solution would be correct as per A2 specification and you would not loose points. 
> 
>  
> 
> But, yes, I do believe that from an API it is clearly better to avoid the cast (because it is unchecked and you could get it wrong).
> 
>  
> 
> Now, you are right that I am only showing to lines of client code, what if the implementation of one was much simpler than the other.  That is a tradeoff and may well be a reason to pick one over the other.
> 
>  
> 
> Without proper support for generics there is no perfect answer.

Either direction is fine with the professors, but I personally ask you, please, can't we just add a small subclass with 4 functions? Just for this assignment? It would make our lives much easier.

**Comment by andrewstam** [comment]
Thanks for your comment, that helps clear things up. I think we had the same basic idea in mind, that a subclass would be ideal for implementing a Queue of Strings specifically, we just weren't sure if it made most sense as part of the API or left up to implementation details. After reading your comments and Piazza quotes, we're now convinced that it makes more sense for this assignment in particular to include a StrQueue subclass in our API rather than keeping it out of our interface. We initially interpreted the assignment specification in a different way, so thank you again for the clarification. Avoiding casting definitely seems ideal.

As for the string.h file, we want to use the given API from Piazza (see [here](https://piazza.com/class/k51bluky59n2jr?cid=345)) because the Professors suggested to get all spec  teams to agree on a common API for String and Object. This was a fairly recent and popular post, so we think it'd be best to use that rather than what you provided on your pull request.

We'll also update our tests to use the new StrQueue subclass for any Queue of Strings.
